### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by mgrossmann** [zowe/zowe-client-java-sdk#105]
Hello all,

First of all I would like to thank you for all your work on this project. I would like to use it in the following project. [zowe-gradle-plugin](https://github.com/zowe-plugin-for-gradle/zowe-plugin-for-gradle ) 
However, since I am primarily interested in the USS functions of Zowe, I have looked at your sources to start with the USS extensions if necessary. I noticed that you make excessive use of Optional<>. 
I was surprised that you also use Optional as a parameter in the constructor and in methods. To my knowledge this is an anti-pattern. Are there any reasons that make this necessary? 

Best
Mike

**Comment by frankgiordano** [comment]
Was my reply satisfactory? May I close this issue? BTW please star the project for support. Regards!

**Comment by mgrossmann** [comment]
Hi Frank,

sorry for the late reply. Yes, of course. Your answer is great. :) 
I will have to discuss this topic with my employer. 

Best
Mike
