### ISSUE TITLE
getRetCode() for completed job is empty

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#115]
Job.getRetCode() is always returning an empty string.

For example:
`Job mountJob = submitJobs.submitJcl(mountJCL.toString(), null, null);
        mountJob = monitorJobs.waitForJobStatus(mountJob, JobStatus.Type.OUTPUT);
        System.out.println("Return code is: "  + mountJob.getRetCode());`

Return code is: Optional.empty

**Comment by frankgiordano** [comment]
Thanks for the issue and good catch!
