### ISSUE TITLE
ZOSMF package to handle z/OSMF information retrieval.

### ISSUE THREAD

**Issue by Nurkambay** [zowe/zowe-client-java-sdk#13]

**Comment by frankgiordano** [comment]
See https://www.ibm.com/docs/en/zos/2.4.0?topic=services-zosmf-information-retrieval-service

**Comment by frankgiordano** [comment]
**Outline**

- Create a “zosmf” package in the github project.
- Create CheckStatus class which contains getZosmfInfo(); method that performs a REST API call to the backend zosmf instance and returns a JSON response.
- Create ListDefinedSystems class which contains listDefinedSystems();  method that performs a REST API call to the backend zosmf instance and returns a JSON response.

Example:

      CheckStatus checkStatus = new CheckStatus(connection);    // new CheckStatus(ZOSConnection connection);
      System.out.println(checkStatus.getZosmfInfo());

See https://www.ibm.com/docs/en/zos/2.4.0?topic=services-zosmf-information-retrieval-service

**Comment by frankgiordano** [comment]
done.
