### ISSUE TITLE
ZosDsnList should throw Exception

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#142]
ZosDsnList squashes exceptions thrown in listDsn and listMembers.

For example, if I have:

`List<String> members = zosDsnList.listMembers(invalidDatasetName, parms);`

My only indication that the dataset name does not exist or is invalid is by checking the output.  These methods should throw the exception discovered by UtilDataset.checkHttpErrors.

**Comment by frankgiordano** [comment]
I assigned this issue to you for resolution as discussed offline remove the outer try catch and propagate the exception. thanks.
