### ISSUE TITLE
ZosDsnList should verify the dataset input

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#143]
We know what a valid dataset looks like.  The methods in ZosDsnList (and potentially other areas) should validate the dataset name before building the z/OSMF URL.

Segment naming rules
            - A data set name must be composed of at least two joined character segments (qualifiers), separated by a
            period (.); for example, HLQ.ABC.XYZ.
            - A data set name cannot be longer than 44 characters.
            - A data set name cannot contain two successive periods; for example, HLQ..ABC.
            - A data set name cannot end with a period.
            - Each segment in a data set name represents a level of qualification. For example, the first segment
            represents the high-level qualifier (HLQ), and the last segment represents the lowest-level qualifier (LLQ).
            - A segment cannot be longer than eight characters.
            - The first segment character must be either a letter or one of the following three special characters: #,
             @, $.
            - The remaining seven characters in a segment can be letters, numbers, special characters (only #, @, or
            $), or a hyphen (-).
            - A data set name cannot contain accented characters (à, é, è, and so on).

**Comment by corinned** [comment]
Currently, special characters and a long input are failing:

`List<String> invalidDatasetNames = Arrays.asList(
                "DSNAME.NOTEXIST",
                "DSNAME.ITSTOOLONG.DS",
                "DSNAME",
                Configuration.CAW0JCL_DSName.replaceAll("\\.", "\\.\\."),
                Configuration.CAW0JCL_DSName + ".",
                //"DSNAME.DS%^&.DS", // Failing
                //"DSNAME.VERYLONG.MORE.THAN.FORTY.FOUR.CHARS.LONG.INVALID", // Failing
                "DSNAME.0123.DS"
                );

        for (String invalidDatasetName:invalidDatasetNames) {
            Exception exception = assertThrows(Exception.class, () -> {
                // Dataset does not exist
                List<String> members = zosDsnList.listMembers(invalidDatasetName, parms);
                assertTrue(members.size()==0);
            });

            assertTrue(exception.getMessage().contains("You may have specified an invalid or non-existent data set."));
        }`

**Comment by frankgiordano** [comment]
Thanks for noting this issue. Good catch! I have seen the @Tests you implemented in the recent PR comments related to this. You may add them to our formal test package in a future PR if you want. I will assign this issue to you as I believe you are working on a new PR request related to this. Let me know otherwise. Thanks again!

**Comment by corinned** [comment]
@frankgiordano do you think the best approach is a static method in UtilDataset?

**Comment by frankgiordano** [comment]
@corinned UtilDataset is a good place to added it there.

**Comment by frankgiordano** [comment]
PR #152 resolves this issue.
