### ISSUE TITLE
ZosDsn.writeDsn returns Optional error with member name prefix #

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#151]
A member name may start with the character #.

This call will return 404 and give an unexpected error.

12:23:00.828 [main] DEBUG zosfiles.ZosDsn - https://ca31:1443/zosmf/restfiles/ds/NATCO02.TESTDATA(#SPECL2)
12:23:01.240 [main] DEBUG rest.TextPutRequest - TextGetRequest::httpPut - Response statusCode 404, Response HttpResponseProxy{HTTP/1.1 404 Not Found [X-Powered-By: Servlet/3.1, X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, Strict-Transport-Security: max-age=31536000; includeSubDomains, Content-Type: application/json; charset=UTF-8, Content-Length: 62, X-IBM-Txid: tx000000000005F4EC, Content-Language: en-US, Set-Cookie: jwtToken=eyJraWQiOiJvekdfeVNNSFJzVlFGbU4xbVZCZVMtV3RDdXBZMXItSzdld2JlbjA5SUJnIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic3ViIjoibmF0Y28wMiIsInVwbiI6Im5hdGNvMDIiLCJncm91cHMiOlsiRlJBTUVXS0ciLCJDSE9SR1JQMiIsIkNIT1JHUlAzIiwiSVpVVU5HUlAiLCJJWlVTRUNBRCIsIkRBQVNHUlAiXSwicmVhbG0iOiJTQUZSZWFsbSIsImlzcyI6InpPU01GIiwiZXhwIjoxNjMxMzA2MTAyLCJpYXQiOjE2MzEyNzY3MDJ9.bYfeglRgOAhDC9VGaoYJOD90ii_1x2AHEEwHFvDKsZHxPfeltRsSrgbw7-7gHyNJby0f9xHC4j1h1RkDK4kZRhDHALYOAB1fvHKVmddKdacW0dw1M8nCUg2M6bnvMW2criJazqN1UD5OcgWsgUmfnq2Lyn5QET49LcC03tizCH4l8AM7Xka59vEMUPAVVTDIngGYpd-WywbQJ5QjeKAGt2Rjw2TLNbTr26CL4D4cDYXnjUtfiL7FwFrOX4DPpITiZdI7fxjhf302a6Cr9Kh1WluC3pBAsJnVjbEaIoC62lw_l6xobNcscZ8BctXut85DT03l3uuOo1eyiLsr6R0WqQ; Path=/; Secure; HttpOnly, Set-Cookie: LtpaToken2=2x+558vpLaSzmRX/VObK8v0DiDGN3X09NENbVxasR+RtSDl4Aog+U5cyFVUSe5Rz9Fb5Go/PEKOCA8pVavKV2JINMPCnfyspF4MwEqRcwFgH9nHh/Jq7oRM/oD6hDjWFpXa1Mn8Bx+ViAg6t1y+JCj27euIUhNuAA3to9S532GjYMkDk4/1xF159nNidpN53jFr20hhmahIgX/cFGJ96Sxk44QnraJlbBbvA35tb5KCT2JiqF/oWxHFAa1utqqgApEvq/9+1tfyk7G7Q30ZBGHWiVkhDYwQesseAa6rgZnPaYc0zHmyY9GjEdDy7WL85; Path=/; Secure; HttpOnly, Connection: Close, Date: Fri, 10 Sep 2021 16:23:01 GMT, Expires: Thu, 01 Dec 1994 16:00:00 GMT, Cache-Control: no-cache="set-cookie, set-cookie2"] ResponseEntityProxy{[Content-Type: application/json; charset=UTF-8,Content-Length: 62,Chunked: false]}}
**java.lang.Exception: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
	at utility.UtilDataset.checkHttpErrors(UtilDataset.java:65)
	at zosfiles.ZosDsn.writeDsn(ZosDsn.java:77)
	at ZosDsnListTest.setUp(ZosDsnListTest.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)**

**Comment by corinned** [comment]
A similar issue occurs with a dataset name that begins with # for listMembers().

For example: 13:29:24.168 [main] DEBUG zosfiles.ZosDsnList - https://ca31:1443/zosmf/restfiles/ds/DSNAME.#NOEXIST/member
13:29:24.607 [main] DEBUG rest.JsonGetRequest - JsonGetRequest::httpGet - Response statusCode 500, Response HttpResponseProxy{HTTP/1.1 500 Internal Server Error [X-Powered-By: Servlet/3.1, X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, Strict-Transport-Security: max-age=31536000; includeSubDomains, Pragma: no-cache, Content-Type: application/json; charset=UTF-8, Content-Length: 222, X-IBM-Txid: tx000000000005F7A3, Content-Language: en-US, Set-Cookie: jwtToken=eyJraWQiOiJvekdfeVNNSFJzVlFGbU4xbVZCZVMtV3RDdXBZMXItSzdld2JlbjA5SUJnIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic3ViIjoibmF0Y28wMiIsInVwbiI6Im5hdGNvMDIiLCJncm91cHMiOlsiRlJBTUVXS0ciLCJDSE9SR1JQMiIsIkNIT1JHUlAzIiwiSVpVVU5HUlAiLCJJWlVTRUNBRCIsIkRBQVNHUlAiXSwicmVhbG0iOiJTQUZSZWFsbSIsImlzcyI6InpPU01GIiwiZXhwIjoxNjMxMzA2MTAyLCJpYXQiOjE2MzEyNzY3MDJ9.bYfeglRgOAhDC9VGaoYJOD90ii_1x2AHEEwHFvDKsZHxPfeltRsSrgbw7-7gHyNJby0f9xHC4j1h1RkDK4kZRhDHALYOAB1fvHKVmddKdacW0dw1M8nCUg2M6bnvMW2criJazqN1UD5OcgWsgUmfnq2Lyn5QET49LcC03tizCH4l8AM7Xka59vEMUPAVVTDIngGYpd-WywbQJ5QjeKAGt2Rjw2TLNbTr26CL4D4cDYXnjUtfiL7FwFrOX4DPpITiZdI7fxjhf302a6Cr9Kh1WluC3pBAsJnVjbEaIoC62lw_l6xobNcscZ8BctXut85DT03l3uuOo1eyiLsr6R0WqQ; Path=/; Secure; HttpOnly, Set-Cookie: LtpaToken2=2x+558vpLaSzmRX/VObK8v0DiDGN3X09NENbVxasR+RtSDl4Aog+U5cyFVUSe5Rz9Fb5Go/PEKOCA8pVavKV2JINMPCnfyspF4MwEqRcwFgH9nHh/Jq7oRM/oD6hDjWFpXa1Mn8Bx+ViAg6t1y+JCj27euIUhNuAA3to9S532GjYMkDk4/1xF159nNidpN53jFr20hhmahIgX/cFGJ96Sxk44QnraJlbBbvA35tb5KCT2JiqF/oWxHFAa1utqqgApEvq/9+1tfyk7G7Q30ZBGHWiVkhDYwQesseAa6rgZnPaYc0zHmyY9GjEdDy7WL85; Path=/; Secure; HttpOnly, Connection: Close, Date: Fri, 10 Sep 2021 17:29:24 GMT, Expires: Thu, 01 Dec 1994 16:00:00 GMT, Cache-Control: no-store, no-cache=set-cookie] ResponseEntityProxy{[Content-Type: application/json; charset=UTF-8,Content-Length: 222,Chunked: false]}}


This should return 404, not 500.

**Comment by corinned** [comment]
URLEncoder.encode(data, "UTF-8"); will format the data correctly.

**Comment by frankgiordano** [comment]
@corinned so our Util.encodeURIComponent would work?

**Comment by frankgiordano** [comment]
I will open a generic URI encoder issue to cover the entire code base.

**Comment by corinned** [comment]
Yes, Util.encodeURIComponent worked.

**Comment by frankgiordano** [comment]
Great. I added this util method early on but we haven't implemented it at the needed places. I opened a generic issue to cover all the code base. Thanks for the PR to cover the zosfiles package.
