### ISSUE TITLE
issueTsoCommand returns NullPointerException

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#165]
Run: 
`IssueTso issueTso = new IssueTso(connection);
        IssueResponse issueResponse = issueTso.issueTsoCommand(accountNum, command);`

NullPointerException on params in StartTso in the first line of the method:

`private StartTsoParams setDefaultAddressSpaceParams(StartTsoParams params, String accountNumber) {
        String proc = params.getLogonProcedure().orElse(TsoConstants.DEFAULT_PROC);
        String chset = params.getCharacterSet().orElse(TsoConstants.DEFAULT_CHSET);
        String cpage = params.getCodePage().orElse(TsoConstants.DEFAULT_CPAGE);
        String rowNum = params.getRows().orElse(TsoConstants.DEFAULT_ROWS);
        String cols = params.getColumns().orElse(TsoConstants.DEFAULT_COLS);
        String rSize = params.getRegionSize().orElse(TsoConstants.DEFAULT_RSIZE);
        return new StartTsoParams(proc, chset, cpage, rowNum, cols, accountNumber, rSize);
    }`

**Comment by corinned** [comment]
Could potentially add at the beginning of the method:

`if (params==null) {
            params=new StartTsoParams(null,null,null,null,null,null,null);
        }`

**Comment by frankgiordano** [comment]
Thanks for reporting this issue. To resolve this issue, we can add a default constructor to StartTsoParams and Optional.empty() assignment to each StartTsoParams  class variable member and then we can do the following in method setDefaultAddressSpaceParams:
if (params == null) params = new StartTsoParams();

**Comment by frankgiordano** [comment]
I checked in the code as I described please test if you can.
