### ISSUE TITLE
Should MonitorJobs waitForJobMessage continue running until timeout if job not running.

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#177]
Should the waitForJobMessage method run if the job isn't running, meaning it exists but in OUTPUT status?
Should the waitForJobMessage method stop running when a job ends running and is in OUTPUT status or let it run until timeout reaches?

**Comment by frankgiordano** [comment]
I will work on adding a status check sometime in the near future. If anyone in the community wants to take this on, please update this issue and I will assign this to you.

**Comment by frankgiordano** [comment]
Assigned this issue to me.

**Comment by frankgiordano** [comment]
I am currently working on this issue which made me spawn a few other issues to add additional enhancements to help with this issue via issues #179 #180.

**Comment by frankgiordano** [comment]
The new behavior that I will check in shortly for this issue will be the following:
When executing waitForJobMessage for a Job that exists but not running in an OUTPUT status if will do one scan of its job output for the message and report if it is found. If not found the second loop of scanning will exit the method as a false value as the job is not in a running state. 
When executing waitForJobMessage for a Job that exists and is running in a non OUTPUT status, it will continue to loop and scan the job output until it finds the message in question or the wait timeout value is reached.

**Comment by corinned** [comment]
"When executing waitForJobMessage for a Job that exists and is running in a non OUTPUT status, it will continue to loop and scan the job output until it finds the message in question or the wait timeout value is reached."

What if the job stops while you are scanning?  Does it fall back to this behavior?

"When executing waitForJobMessage for a Job that exists but not running in an OUTPUT status it will perform one scan of its job output for the message and report if it is found. If not found the second loop of scanning will exit the method with a false value as the job is not in a running state."

**Comment by frankgiordano** [comment]
In the first scenario I described I forgot to add it will also end waiting for a message to appear if it hasn't appeared yet and the  job status changes to OUTPUT.
