### ISSUE TITLE
ZosDsnCopy.copy() does not create a new dataset

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#196]
Create a valid, sequential dataset and attempt to copy it to a dataset name that does not exist.

```
copyParams = new CopyParams.Builder().fromDataSet(testSeqDatasetFrom).toDataSet(testSeqDatasetTo).replace(true).build();
zosDsnCopy.copy(copyParams);
```

Returns with http error code 500.

If we do not create a dataset as part of the copy, then the replace property in CopyParams is not going to be utilized properly.    If replace==false, then copy() will fail if the dataset exists or does not exist.  The only combination of replace and exists that will currently work is when both are true.

Currently:

replace | exists | outcome
true | true | overwrite
false | true | fail
true | false | fail
false | false | fail

If I were using this, I would expect something more like:

replace | exists | outcome
true | false | overwrite
false | true | fail
true | false | create
false | false | create

**Comment by frankgiordano** [comment]
search for replace:true|false in the following link which gives us some info.

https://www.ibm.com/docs/en/zos/2.1.0?topic=interface-zos-data-set-member-utilities

I will try to code this up on nodejs and see how it behaves.

**Comment by frankgiordano** [comment]
I coded this situation in NodeJS:

    const session: Session = ZosmfSession.createBasicZosmfSession(defaultZosmfProfile)

    // Create Options
    const dataset: string = "FG892105.NEW.DATASET";
    const dataSetType = CreateDataSetTypeEnum.DATA_SET_SEQUENTIAL;
    const createOptions: ICreateDataSetOptions = {
        primary: 10,
        secondary: 1,
        alcunit: "TRK",
        lrecl: 80
    };

    let response: IZosFilesResponse;
    response = await Create.dataSet(session, dataSetType, dataset, createOptions);
    console.log(response);

    const todataset: string = "FG892105.NEW.DATASET";
    const fromdataset: string = "FG892105.OLD.DATASET";
    // const dataSetType = CreateDataSetTypeEnum.DATA_SET_CLASSIC;
    const toDataSet: IDataSet =
    {
        dataSetName: todataset
    };
    const fromDataSet: IDataSet =
    {
        dataSetName: fromdataset
    };
    const options: ICopyDatasetOptions = {
        fromDataSet: fromDataSet,
        replace: true
    }
    response = await Copy.dataSet(session, toDataSet, options);
    console.log(response);

**Comment by frankgiordano** [comment]
@corinned See above NodeJS example. It successfully creates a new Dataset with the "Create" function". I then use this to copy it to another non-existing Dataset. It fails. 

{ success: true, commandResponse: 'Data set created successfully.' }
RestClientError: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 6
rc:       8
reason:   386400778
message:  ISPF LMINIT - data set not found
details:
  - 'FG892105.OLD.DATASET' was not found in catalog.


    at ZosmfRestClient.populateError (C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:507:16)
    at ZosmfRestClient.onEnd (C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:427:31)
    at IncomingMessage.<anonymous> (C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:362:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  mDetails: {
    msg: 'z/OSMF REST API Error:\n' +
      'Rest API failure with HTTP(S) status 500\n' +
      'category: 6\n' +
      'rc:       8\n' +
      'reason:   386400778\n' +
      'message:  ISPF LMINIT - data set not found\n' +
      'details: \n' +
      "  - 'FG892105.OLD.DATASET' was not found in catalog.\n" +
      '\n',

**Comment by frankgiordano** [comment]
@corinned As such the behavior is working the same as NodeJS SDK. I don't think this is a defect per se. Thoughts?

**Comment by corinned** [comment]
The IBM doc helped a lot for replace:

Applicable with from-dataset. When from-file specified,ignored unless from-file/type=text. if true, members in the target dataset are replaced. if false(default), like named members are not copied and an error is returned.

That leads me to believe that replace is relevant when dealing with members, not a sequential dataset.  Let me try out some calls with partitioned datasets instead.

**Comment by frankgiordano** [comment]
@corinned as this behave the same as nodeJS I will close this issue. Please reopen if you think otherwise.
