### ISSUE TITLE
ZosDsnList only returns dataset names

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#211]
The z/OSMF API allows us to get lots of information back about the datasets when utilizing the X-IBM-Attributes as base, vol, total: https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-list-zos-data-sets-system.  We are currently only utilizing dsname.

1. listDsn should return a List of Datasets, not a List of Strings, so that we can access the data about the datasets if X-IBM-Attribute is base, for example.  This returns information such as: {"dsorg":"PO","recfm":"FB","used":"60","dsntp":"PDS","edate":"***None***","lrecl":"80","sizex":"240","vol":"CCSQAC","cdate":"2011\/08\/15","dev":"3390","migr":"NO","catnm":"ICF.CCSQA.CAT","mvol":"N","rdate":"2021\/10\/29","dsname":"CCSQA.ASM.JCL","vols":"CCSQAC","extx":"2","ovf":"NO","spacu":"CYLINDERS","blksz":"32720"}

2. setHeaders checks if params.getAttributes().isPresent(), but doesn't use the value there.  Instead, it always uses ZosmfHeaders.HEADERs.get("X_IBM_ATTRIBUTES_BASE").  Should this be configurable to dsname, base, vol, and total?

**Comment by frankgiordano** [comment]
Hi Corinne, thanks for the issue. I made a change for base and vol to work via the listparams in a way that makes this more useful. Please check it out. I recently made a change to only return dataset name string and removed the dataset object json conversion as I thought the functionality to retrieve all dataset properties wasn't available. I was wrong and reverted that conversion back. Btw I couldn't get Total to work. Maybe you can..
