### ISSUE TITLE
Job missing stepData and reasonNotRunning

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#213]
stepData and reasonNotRunning are always null in zosjobs.response.Job.

**Comment by corinned** [comment]
Looks like step data requires a separate rest call:

GET /zosmf/restjobs/jobs/<jobname>/<jobid>?[step-data=Y|N]
GET /zosmf/restjobs/jobs/<correlator>?[step-data=Y|N]

**Comment by frankgiordano** [comment]
done. This is releases in 1.0.15 Jar version

**Comment by frankgiordano** [comment]
Had to make some minor changes. Use version 1.0.16 for complete feature of stepdata usage.

**Comment by frankgiordano** [comment]
@corinned  For reasonNotRunning this is an unused attribute that I copied over from NodeJS Job object but it isn't used in the NodeJS SDK at all. In addition, I don't see any IBM documentation for z/OSMF Job retrieval that references this attribute . AS such, I will remove it from the project.
