### ISSUE TITLE
Update zosfiles package with USS CRUD operations. 

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#222]
Implement REST APIs call to manipulate USS (Unix System Services) file(s) and directories that are defined here:
https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-write-data-zos-unix-file. 
Implement List, Write, Create and Delete operations with REST APIs. 
Just FYI don't forget recursive header See https://github.com/zowe/zowe-client-python-sdk/issues/85

**Comment by Freedisch** [comment]
@frankgiordano Hello, I'm Freedisch Thibaut Batale and I'm really interested about working on this project as an LFX mentee for this summer. 
Considering the description of the project 
Is this issue part of the work that has to be done for this summer? I can start exploring it

**Comment by frankgiordano** [comment]
@Freedisch Hi I dont see your application on the LFX website. Please submit your application so you can be considered!

**Comment by hindu-muppala** [comment]
@frankgiordano ,Hello this is hindu ,java developer. Can I take up this issue to get start working for LFX mentee for this summer?.

**Comment by frankgiordano** [comment]
@hindu-muppala Hello Hindu, thank you for the interest. At this time, candidates who have applied to this project for a summer internship on the LFX page are being considered. One person will be selected to work on this project with me this summer.

**Comment by frankgiordano** [comment]
Closing out this issue as I create an issue for each USS operation: #270 #271 #272 #273 #274 #275 #276 #277 #278 #279 #280
