### ISSUE TITLE
apiVersion does not exist

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#235]
`
CheckStatus checkStatus = new CheckStatus(connection);
ZosmfInfoResponse zosmfInfoResponse = checkStatus.getZosmfInfo();
String apiVersion = zosmfInfoResponse.getApiVersion().get();
`
returns:

java.util.NoSuchElementException: No value present

However, the JSON output indicates that the value is present:
{"zos_version":"04.28.00","zosmf_port":"1443","zosmf_version":"28","zosmf_hostname":"_xxxx_","plugins":[{"pluginVersion":"HSMA250;PH38968;2021-11-17T02:45:42","pluginDefaultName":"z\/OS Operator Consoles","pluginStatus":"ACTIVE"},_....._],"zosmf_saf_realm":"SAFRealm","zosmf_full_version":"28.0",**"api_version":"1"**}

**Comment by frankgiordano** [comment]
Thanks for finding this issue.
