### ISSUE TITLE
CancelJobs with empty version

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#246]
The following call is not getting flagged as an invalid version:

    cancelJobs.cancelJob(jobname, jobid, "")

CancelJobs is only picking up version=null or an incorrect version string, not an empty string in cancelJobsCommon().

Additionally, when an invalid version is found, it should throw a IllegalArgumentException, not a generic Exception.

**Comment by corinned** [comment]
Tests are:  

        Exception exception = assertThrows(IllegalArgumentException.class, () ->
                cancelJobs.cancelJob(null, jobid, "1.0"));
        assertTrue(exception.getMessage().contains("job name not specified"));

        exception = assertThrows(IllegalArgumentException.class, () ->
                cancelJobs.cancelJob("", jobid, "1.0"));
        assertTrue(exception.getMessage().contains("job name not specified"));

        exception = assertThrows(IllegalArgumentException.class, () ->
                cancelJobs.cancelJob(jobname, null, "1.0"));
        assertTrue(exception.getMessage().contains("job id not specified"));

        exception = assertThrows(IllegalArgumentException.class, () ->
                cancelJobs.cancelJob(jobname, "", "1.0"));
        assertTrue(exception.getMessage().contains("job id not specified"));

        exception = assertThrows(IllegalArgumentException.class, () ->
                cancelJobs.cancelJob(jobname, jobid, "12.3"));
        assertTrue(exception.getMessage().contains("invalid version specified"));

        exception = assertThrows(IllegalArgumentException.class, () ->
                cancelJobs.cancelJob(jobname, jobid, ""));
        assertTrue(exception.getMessage().contains("invalid version specified"));

**Comment by frankgiordano** [comment]
@corinned if a null value is sent for version then the following is defaulted:

        String version = params.getVersion().orElse(JobsConstants.DEFAULT_CANCEL_VERSION);

maybe we should allow the same behavior if the end user sends in an empty "" string value use default too..
I would think if an end user sends an empty string user expects the code to default the value too. This is just a thought. I have no issue to force a valid value if they decide not to use null.

**Comment by frankgiordano** [comment]
@corinned if we go that route it would be something like

        if (builder.version.isEmpty()) {
            this.version = Optional.empty();
        } else {
            this.version = Optional.ofNullable(builder.version);
        }

inside constructor     private ModifyJobParams(ModifyJobParams.Builder builder) {

then the code as is will default version number for empty string version or null version..

**Comment by corinned** [comment]
> @corinned if a null value is sent for version then the following is defaulted:
> 
> ```
>     String version = params.getVersion().orElse(JobsConstants.DEFAULT_CANCEL_VERSION);
> ```
> 
> maybe we should allow the same behavior if the end user sends in an empty "" string value use default too.. I would think if an end user sends an empty string user expects the code to default the value too. This is just a thought. I have no issue to force a valid value if they decide not to use null.

I thought about that too... but we generally throw an Exception for null and empty, so this would follow the same convention.
