### ISSUE TITLE
getJob by jobID does not return stepData

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#252]
GetJobs.getJob(String jobID) does not return stepData[].  This means that you will not receive the complete Job object when querying by Job ID.

For example:

        Job job = submitJobs.submitJob(new Member(partitionedDataset, "BR14").toString());
        Job submittedJob = monitorJobs.waitForJobOutputStatus(job);
        Job retrievedJob = getJobs.getJob(submittedJob.getJobId().get());
 
Here I would expect that  submittedJob==retrievedJob.  However, retrievedJob is missing step-data.

**Comment by frankgiordano** [comment]
@corinned I noticed that the NodeJS SDK does not return stepdata for this call either.  I think it is safe to say only getStatus method will return stepdata. As long as getStatus is documented as such, the end user will be able to seek it out accordingly. I think we can close this issue.

**Comment by frankgiordano** [comment]
This issue has been used to document stepData usage better with updated java doc and to have GetStatusForJob method to return step data info for job.
