### ISSUE TITLE
Write data to a z/OS UNIX file

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#270]
Create REST API for the following:
https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-write-data-zos-unix-file

**Comment by frankgiordano** [comment]
Use the following package zowe.client.sdk.zosfiles.uss.write to create classes there for this issue's implementation.

**Comment by frankgiordano** [comment]
Update: use branch "methods" and "zowe.client.sdk.zosfiles.uss.methods" package to implement new class for this api

**Comment by frankgiordano** [comment]
implement in zowe.client.sdk.zosfiles.uss.methods.UssWrite class

**Comment by kostrja** [comment]
commenting to assign

**Comment by kostrja** [comment]
completed work in reference to PR 303

**Comment by frankgiordano** [comment]
marking as done
