### ISSUE TITLE
Retrieve the contents of a z/OS UNIX file

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#271]
Create a REST API for the following:
https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-retrieve-contents-zos-unix-file

**Comment by frankgiordano** [comment]
Use the following package zowe.client.sdk.zosfiles.uss.get to create classes there for this issue's implementation.

**Comment by frankgiordano** [comment]
Update: use branch "methods" and "zowe.client.sdk.zosfiles.uss.methods" package to implement new class for this api

**Comment by frankgiordano** [comment]
implement in zowe.client.sdk.zosfiles.uss.methods.UssGet class

**Comment by frankgiordano** [comment]
@kostrja Hi Jimmy, please add a comment to this issue. I will then assign to you as you are actively working on this issue.

**Comment by kostrja** [comment]
commenting to assign

**Comment by frankgiordano** [comment]
done
