### ISSUE TITLE
Create a z/OS UNIX file or directory

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#273]
Create a REST API for the following:
https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-create-unix-file-directory

**Comment by frankgiordano** [comment]
Use the following package zowe.client.sdk.zosfiles.uss.create to create classes there for this issue's implementation.

**Comment by frankgiordano** [comment]
Update: use branch "methods" and "zowe.client.sdk.zosfiles.uss.methods" package to implement new class for this api

**Comment by frankgiordano** [comment]
done

**Comment by frankgiordano** [comment]
@kostrja james add a comment to this issue. Once you do I can select you as an assignee to mark you credit.

**Comment by kostrja** [comment]
commenting to assign
