### ISSUE TITLE
Delete a z/OS UNIX file or directory

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#274]
Create a REST API for the following:
https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-delete-unix-file-directory

**Comment by frankgiordano** [comment]
FYI be aware of the following when working on this issue: 
https://github.com/zowe/zowe-client-python-sdk/issues/85

**Comment by frankgiordano** [comment]
Use the following package zowe.client.sdk.zosfiles.uss.delete to create classes there for this issue's implementation.

**Comment by frankgiordano** [comment]
done

**Comment by frankgiordano** [comment]
@kostrja James add a comment here so I can assign this issue to you for credit.

**Comment by kostrja** [comment]
commenting to assign
