### ISSUE TITLE
Change tag a z/OS UNIX file system

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#286]
Create chtag REST API see:
https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-zos-unix-file-utilities

**Comment by frankgiordano** [comment]
use branch "methods" and "zowe.client.sdk.zosfiles.uss.methods" package to implement new class for this api

**Comment by frankgiordano** [comment]
implement in zowe.client.sdk.zosfiles.uss.methods.UssChTag class

**Comment by kostrja** [comment]
commenting to assign

**Comment by frankgiordano** [comment]
@kostrja add an update to this issue and I will then assign it to you.

**Comment by kostrja** [comment]
commenting to assign
