### ISSUE TITLE
Extend attributes a z/OS UNIX file system

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#288]
Create extattr REST API see:
https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-zos-unix-file-utilities

**Comment by frankgiordano** [comment]
use branch "methods" and "zowe.client.sdk.zosfiles.uss.methods" package to implement new class for this api

**Comment by frankgiordano** [comment]
implement in zowe.client.sdk.zosfiles.uss.methods.UssExtAttr class

**Comment by kostrja** [comment]
commenting to assign
