### ISSUE TITLE
Validate permission mode input in UssCreate

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-client-java-sdk#298]
Validate input consist of 9 characters and each character can only be r, w, x or - character. Throw an exception with a clear description of invalid permission mode provided to the end user. This issue came about due to the vague IBM z/OSMF JSON error response related to invalid permission value.

**Comment by frankgiordano** [comment]
@kostrja hi jimmy, please comment here so I can assign this issue to you.

**Comment by kostrja** [comment]
Commenting to assign
