### ISSUE TITLE
List datasets and members

### ISSUE THREAD

**Issue by Nurkambay** [zowe/zowe-client-java-sdk#6]
- List datasets and members:
https://github.com/zowe/zowe-client-swift-sdk/blob/master/Sources/ZoweSDK/zosfiles/src/ZOSFiles%2BList.swift

**Comment by frankgiordano** [comment]
Lets keep this open. Lets cover the unit tests for this which have not been generated yet. And I believe we will need to refactor to avoid static usage and use new object creation so it can be mocked and tested better.

**Comment by frankgiordano** [comment]
see #37 you will probably need to convert before adding unit tests.. @Nike682631 @Nurkambay

**Comment by Nurkambay** [comment]
Split into 3 issues. This part is done.
